services:
  agent-api:
    build:
      context: .
      args:
        WORKDIR_PATH: ${WORKDIR_PATH}
        AGENT_API_PORT: ${AGENT_API_PORT}
    env_file:
      - .env
    ports:
      - "${AGENT_API_PORT}:${AGENT_API_PORT}"
    volumes:
      - './:${WORKDIR_PATH}'
    networks:
      - net-system
    depends_on:
      pgsql-business:
        condition: service_healthy
      pgsql-agent:
        condition: service_healthy
  pgsql-business:
    image: 'postgres:17'
    environment:
      POSTGRES_USER: ${BUSINESS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BUSINESS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${BUSINESS_POSTGRES_DB}
    ports:
      - '${BUSINESS_POSTGRES_HOST_PORT}:5432'
    volumes:
      - 'vol-pgsql-business:/var/lib/postgresql/data'
    networks:
      - net-system
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${BUSINESS_POSTGRES_DB}", "-U", "${BUSINESS_POSTGRES_USER}"]
      retries: 3
      timeout: 5s
  pgsql-agent:
    image: 'postgres:17'
    environment:
      POSTGRES_USER: ${AGENT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AGENT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AGENT_POSTGRES_DB}
    ports:
      - '${AGENT_POSTGRES_HOST_PORT}:5432'
    volumes:
      - 'vol-pgsql-agent:/var/lib/postgresql/data'
    networks:
      - net-system
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "${AGENT_POSTGRES_DB}", "-U", "${AGENT_POSTGRES_USER}"]
      retries: 3
      timeout: 5s
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - 'vol-pgadmin:/var/lib/pgadmin'
    networks:
      - net-system
    depends_on:
      pgsql-business:
        condition: service_healthy
      pgsql-agent:
        condition: service_healthy
volumes:
  vol-pgsql-business:
    driver: local
  vol-pgsql-agent:
    driver: local
  vol-pgadmin:
    driver: local
networks:
  net-system:
    driver: bridge
