# internal
from .prompts import (
    INTENT_COMPREHENSION,
    REQUEST_CLASSIFICATION,
    PUNT_RESPONSE,
    ANALYTICAL_REQUIREMENT,
    DIRECT_RESPONSE,
    CONTEXT_DISTILLATION,
    DATA_AVAILABILITY,
    DATA_UNAVAILABILITY_RESPONSE,
    DATA_RETRIEVAL_PLAN,
    DATA_RETRIEVAL_PLAN_FROM_DATA_RETRIEVAL_PLAN_EXECUTION,
    DATA_RETRIEVAL_PLAN_FROM_DATA_RETRIEVAL_PLAN_OBSERVATION,
    DATA_RETRIEVAL_PLAN_OBSERVATION,
    ANALYTICAL_PLAN,
    ANALYTICAL_PLAN_FROM_ANALYTICAL_PLAN_EXECUTION,
    ANALYTICAL_PLAN_FROM_ANALYTICAL_PLAN_OBSERVATION,
    ANALYTICAL_PLAN_OBSERVATION,
    ANALYTICAL_RESULT,
    INFOGRAPHIC_REQUIREMENT,
    ANALYTICAL_RESPONSE,
    INFOGRAPHIC_PLAN,
    INFOGRAPHIC_PLAN_FROM_INFOGRAPHIC_PLAN_EXECUTION,
    INFOGRAPHIC_PLAN_FROM_INFOGRAPHIC_PLAN_OBSERVATION,
    INFOGRAPHIC_PLAN_OBSERVATION,
    SUMMARIZATION,
)

prompt_dict: dict[str, str] = {
    "__intent_comprehension": INTENT_COMPREHENSION,
    "__request_classification": REQUEST_CLASSIFICATION,
    "__punt_response": PUNT_RESPONSE,
    "__analytical_requirement": ANALYTICAL_REQUIREMENT,
    "__direct_response": DIRECT_RESPONSE,
    "__context_distillation": CONTEXT_DISTILLATION,
    "__data_availability": DATA_AVAILABILITY,
    "__data_unavailability_response": DATA_UNAVAILABILITY_RESPONSE,
    "__data_retrieval_plan": DATA_RETRIEVAL_PLAN,
    "__data_retrieval_plan_from_data_retrieval_plan_execution": DATA_RETRIEVAL_PLAN_FROM_DATA_RETRIEVAL_PLAN_EXECUTION,
    "__data_retrieval_plan_from_data_retrieval_plan_observation": DATA_RETRIEVAL_PLAN_FROM_DATA_RETRIEVAL_PLAN_OBSERVATION,
    "__data_retrieval_plan_observation": DATA_RETRIEVAL_PLAN_OBSERVATION,
    "__analytical_plan": ANALYTICAL_PLAN,
    "__analytical_plan_from_analytical_plan_execution": ANALYTICAL_PLAN_FROM_ANALYTICAL_PLAN_EXECUTION,
    "__analytical_plan_from_analytical_plan_observation": ANALYTICAL_PLAN_FROM_ANALYTICAL_PLAN_OBSERVATION,
    "__analytical_plan_observation": ANALYTICAL_PLAN_OBSERVATION,
    "__analytical_result": ANALYTICAL_RESULT,
    "__infographic_requirement": INFOGRAPHIC_REQUIREMENT,
    "__analytical_response": ANALYTICAL_RESPONSE,
    "__infographic_plan": INFOGRAPHIC_PLAN,
    "__infographic_plan_from_infographic_plan_execution": INFOGRAPHIC_PLAN_FROM_INFOGRAPHIC_PLAN_EXECUTION,
    "__infographic_plan_from_infographic_plan_observation": INFOGRAPHIC_PLAN_FROM_INFOGRAPHIC_PLAN_OBSERVATION,
    "__infographic_plan_observation": INFOGRAPHIC_PLAN_OBSERVATION,
    "__summarization": SUMMARIZATION,
}

__all__ = ["prompt_dict"]
