"""
System prompt registry.

This package centralizes all system-level prompts used during
graph execution, providing a dedicated and inspectable location
for prompt definitions across different orchestration nodes.
"""
from .prompts import (
    INTENT_COMPREHENSION,
    REQUEST_CLASSIFICATION,
    PUNT_RESPONSE,
    ANALYTICAL_REQUIREMENT,
    DIRECT_RESPONSE,
    DATA_AVAILABILITY,
    DATA_UNAVAILABILITY_RESPONSE,
    DATA_RETRIEVAL_PLANNING,
    DATA_RETRIEVAL_PLANNING_FROM_DATA_RETRIEVAL_EXECUTION,
    DATA_RETRIEVAL_PLANNING_FROM_DATA_RETRIEVAL_OBSERVATION,
    DATA_RETRIEVAL_OBSERVATION,
    ANALYTICAL_PLANNING,
    ANALYTICAL_PLANNING_FROM_ANALYTICAL_PLAN_EXECUTION,
    ANALYTICAL_PLANNING_FROM_ANALYTICAL_PLAN_OBSERVATION,
    ANALYTICAL_PLAN_OBSERVATION,
    ANALYTICAL_RESULT,
)

__all__ = [
    "INTENT_COMPREHENSION",
    "PUNT_RESPONSE",
    "REQUEST_CLASSIFICATION",
    "ANALYTICAL_REQUIREMENT",
    "DIRECT_RESPONSE",
    "DATA_AVAILABILITY",
    "DATA_UNAVAILABILITY_RESPONSE",
    "DATA_RETRIEVAL_PLANNING",
    "DATA_RETRIEVAL_PLANNING_FROM_DATA_RETRIEVAL_EXECUTION",
    "DATA_RETRIEVAL_PLANNING_FROM_DATA_RETRIEVAL_OBSERVATION",
    "DATA_RETRIEVAL_OBSERVATION",
    "ANALYTICAL_PLANNING",
    "ANALYTICAL_PLANNING_FROM_ANALYTICAL_PLAN_EXECUTION",
    "ANALYTICAL_PLANNING_FROM_ANALYTICAL_PLAN_OBSERVATION",
    "ANALYTICAL_PLAN_OBSERVATION",
    "ANALYTICAL_RESULT",
]