"""
Docstring for context.system_prompts
"""
from .prompts import (
    ANALYSIS_RESPONSE,
    ANALYSIS_ORCHESTRATION,
    COMPUTATION_PLANNING,
    DATA_UNAVAILABILITY,
    DIRECT_RESPONSE,
    INTENT_COMPREHENSION,
    OBSERVATION,
    PUNT_RESPONSE,
    REQUEST_CLASSIFICATION,
    SELF_CORRECTION,
    SELF_REFLECTION,
    SUMMARIZATION,
)

__all__ = [
    "ANALYSIS_RESPONSE",
    "ANALYSIS_ORCHESTRATION",
    "COMPUTATION_PLANNING",
    "DATA_UNAVAILABILITY",
    "DIRECT_RESPONSE",
    "INTENT_COMPREHENSION",
    "OBSERVATION",
    "PUNT_RESPONSE",
    "REQUEST_CLASSIFICATION",
    "SELF_CORRECTION",
    "SELF_REFLECTION",
    "SUMMARIZATION",
]